import { z } from 'zod'
import { MAX_QUESTIONS } from '../constants/question-limits.js'

const cardPresetSchema = z.enum([
  'enem-a4',
  'school-a4',
  'quiz-20',
  'quiz-45',
  'quiz-60',
  'answer-sheet-4',
  'answer-sheet-5',
])

const omrConfigSchema = z
  .object({
    totalQuestions: z.number().int().positive().max(MAX_QUESTIONS).optional(),
    choicesPerQuestion: z.union([z.literal(2), z.literal(3), z.literal(4), z.literal(5)]).optional(),
    columns: z.number().int().positive().optional(),
    rowsPerColumn: z.number().int().positive().optional(),
    startXRatio: z.number().min(0).max(1).optional(),
    startYRatio: z.number().min(0).max(1).optional(),
    columnGapRatio: z.number().min(0).max(1).optional(),
    rowGapRatio: z.number().min(0).max(1).optional(),
    optionGapRatio: z.number().min(0).max(1).optional(),
    bubbleRadiusRatio: z.number().min(0.001).max(0.2).optional(),
    markThreshold: z.number().min(0).max(1).optional(),
    ambiguityThreshold: z.number().min(0).max(1).optional(),
  })
  .optional()

const cardDefinitionSchema = z.object({
  pageSize: z.literal('A4'),
  totalQuestions: z.number().int().positive().max(MAX_QUESTIONS),
  choicesPerQuestion: z.union([z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
  optionLabels: z.array(z.string().regex(/^[A-Z0-9]$/)).min(2).max(5),
  columns: z.number().int().positive(),
  rowsPerColumn: z.number().int().positive(),
  questionStyle: z.enum(['classic', 'lined', 'minimal']),
  bubbleSize: z.enum(['large', 'medium', 'small']),
  rowSpacing: z.enum(['compact', 'uniform']),
  columnLayoutMode: z.enum(['left', 'distributed']),
  columnGap: z.number().min(0).max(40),
  optionAlignment: z.enum(['auto', 'left', 'right', 'center', 'justify']),
  enableQuestionBlocks: z.boolean(),
  showQuestionBlockTitles: z.boolean(),
  questionBlocks: z.array(
    z.union([
      z.object({
        id: z.string(),
        sectionType: z.literal('objective'),
        readMode: z.literal('answers'),
        startQuestion: z.number().int().positive(),
        endQuestion: z.number().int().positive().max(MAX_QUESTIONS),
        title: z.string(),
        choicesPerQuestion: z.union([z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
        optionLabels: z.array(z.string().regex(/^[A-Z0-9]$/)).min(2).max(5),
        numberingFormat: z.enum(['numeric', 'numericAlpha', 'alphaNumeric', 'numericLower', 'numericDash']),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('open'),
        readMode: z.literal('manual'),
        label: z.string(),
        lines: z.number().int().min(1).max(20),
        lineStyle: z.enum(['line', 'box']),
        linkedToMainQuestion: z.boolean(),
        linkedQuestionNumber: z.number().int().positive().nullable(),
        markerLabel: z.string().max(12),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('math'),
        readMode: z.literal('manual'),
        columns: z.number().int().min(1).max(10),
        showTopInputRow: z.boolean(),
        showColumnHeaders: z.boolean(),
        columnHeaders: z.array(z.string().max(3)).min(0).max(10),
        showColumnSeparators: z.boolean(),
        separatorMode: z.enum(['none', 'comma', 'dot', 'negative', 'negative-comma', 'negative-dot']).optional(),
        columnSeparators: z.array(z.enum(['', '.', ',', '-'])).min(0).max(10),
        linkedToMainQuestion: z.boolean(),
        linkedQuestionNumber: z.number().int().positive().nullable(),
        markerLabel: z.string().max(12),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('image'),
        readMode: z.enum(['ignored', 'manual']),
        imageSrc: z.string().nullable(),
        imageName: z.string().nullable(),
        imageWidth: z.number().int().positive().nullable().optional(),
        imageHeight: z.number().int().positive().nullable().optional(),
        size: z.enum(['auto', '25', '50', '75', '100']),
        align: z.enum(['left', 'center', 'right']),
        isQuestion: z.boolean(),
        linkedToMainQuestion: z.boolean(),
        linkedQuestionNumber: z.number().int().positive().nullable(),
        markerLabel: z.string().max(12),
        mimeType: z.string().optional(),
        fileSize: z.number().int().positive().optional(),
        optimized: z.boolean().optional(),
        originalName: z.string().optional(),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('essay'),
        readMode: z.literal('manual'),
        title: z.string(),
        style: z.enum(['lines', 'box']),
        lines: z.number().int().min(10).max(60),
        highlightStep: z.number().int().min(0).max(20),
        showHeader: z.boolean(),
        showEssayTitleField: z.boolean(),
        showStudentName: z.boolean(),
        showClass: z.boolean(),
        showTestName: z.boolean(),
        showCode: z.boolean(),
        showTeacher: z.boolean(),
        showShift: z.boolean(),
        showDate: z.boolean(),
        showLogo: z.boolean(),
        logoPosition: z.enum(['top-left', 'top-center', 'top-right']),
        showQRCode: z.boolean(),
        qrPosition: z.enum(['bottom-right', 'top-right']),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('label'),
        readMode: z.literal('ignored'),
        text: z.string(),
        align: z.enum(['left', 'center', 'right']),
        size: z.enum(['sm', 'md', 'lg']),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('spacer'),
        readMode: z.literal('ignored'),
        size: z.enum(['sm', 'md', 'lg']),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('pageBreak'),
        readMode: z.literal('ignored'),
      }),
      z.object({
        id: z.string(),
        sectionType: z.literal('signature'),
        readMode: z.literal('ignored'),
        label: z.string(),
        align: z.enum(['left', 'center', 'right']),
        lineWidth: z.enum(['sm', 'md', 'lg']),
      }),
    ]),
  ),
  identification: z.object({
    showStudentName: z.boolean(),
    showStudentCode: z.boolean(),
    showClassroom: z.boolean(),
    showDate: z.boolean(),
    showExamCode: z.boolean(),
    showSignature: z.boolean(),
    showManualIdGrid: z.boolean(),
    extraFields: z.array(z.string()),
  }),
  header: z.object({
    institutionName: z.string(),
    examName: z.string(),
    subtitle: z.string(),
    classroomLabel: z.string(),
    instructions: z.string(),
    showInstructions: z.boolean(),
    omrGuidance: z.string(),
    footerMessage: z.string(),
    footerMessageAlignment: z.enum(['left', 'center', 'right']),
    footerMessageWeight: z.enum(['regular', 'semibold']),
    footerMessageFontSize: z.number().min(7).max(11),
    footerPagePosition: z.enum(['top', 'bottom']),
    footerPageTone: z.enum(['subtle', 'standard']),
    showInstitutionLogo: z.boolean(),
    institutionLogoDataUrl: z.string(),
    logoAlignment: z.enum(['left', 'center', 'right']),
    logoScale: z.number().min(0.6).max(1.2),
    logoMonochrome: z.boolean(),
  }),
})

const cardVisualThemeSchema = z.object({
  visualStyle: z.enum(['institutional', 'vestibular', 'compact']),
  density: z.enum(['compact', 'balanced', 'spacious']),
  softBorders: z.boolean(),
  showSectionSeparators: z.boolean(),
  refinedAlignment: z.boolean(),
  highlightHeader: z.boolean(),
  answerGridStyle: z.enum(['classic', 'lined', 'minimal']),
})

export const createTemplateSchema = z.object({
  name: z.string().min(3),
  examId: z.string().min(1),
  totalQuestions: z.number().int().positive().max(MAX_QUESTIONS),
  presetId: cardPresetSchema,
  definition: cardDefinitionSchema,
  visualTheme: cardVisualThemeSchema,
  omrConfig: omrConfigSchema,
})

export const updateTemplateSchema = createTemplateSchema.extend({
  id: z.string().min(1).optional(),
})

export const templateListQuerySchema = z.object({
  examId: z.string().min(1).optional(),
})
